var CHANGE_VARIABLES_EXTENSIONS = [
  '.js',
  '.html',
  '.mako',
  '.less',
  '.css'
];

var FORCE_SKIPPED_EXTENSIONS = [
  '.min.js',
];

var MAPPING = {
  // BS2 to FA4
  'icon-glass': 'fa fa-glass',
  'icon-music': 'fa fa-music',
  'icon-search': 'fa fa-search',
  'icon-envelope': 'fa fa-envelope',
  'icon-heart': 'fa fa-heart',
  'icon-star': 'fa fa-star',
  'icon-star-empty': 'fa fa-star-o',
  'icon-user': 'fa fa-user',
  'icon-film': 'fa fa-film',
  'icon-th-large': 'fa fa-th-large',
  'icon-th': 'fa fa-th',
  'icon-th-list': 'fa fa-th-list',
  'icon-ok': 'fa fa-check',
  'icon-remove': 'fa fa-times',
  'icon-zoom-in': 'fa fa-search-plus',
  'icon-zoom-out': 'fa fa-search-minus',
  'icon-off': 'fa fa-power-off',
  'icon-signal': 'fa fa-signal',
  'icon-cog': 'fa fa-cog',
  'icon-trash': 'fa fa-trash-o',
  'icon-home': 'fa fa-home',
  'icon-file': 'fa fa-file',
  'icon-time': 'fa fa-clock-o',
  'icon-road': 'fa fa-road',
  'icon-download-alt': 'fa fa-download',
  'icon-download': 'fa fa-arrow-circle-o-down',
  'icon-upload': 'fa fa-arrow-circle-o-up',
  'icon-inbox': 'fa fa-inbox',
  'icon-play-circle': 'fa fa-play-circle-o',
  'icon-repeat': 'fa fa-repeat',
  'icon-refresh': 'fa fa-refresh',
  'icon-list-alt': 'fa fa-list-alt',
  'icon-lock': 'fa fa-lock',
  'icon-flag': 'fa fa-flag',
  'icon-headphones': 'fa fa-headphones',
  'icon-volume-off': 'fa fa-volume-off',
  'icon-volume-down': 'fa fa-volume-down',
  'icon-volume-up': 'fa fa-volume-up',
  'icon-qrcode': 'fa fa-qrcode',
  'icon-barcode': 'fa fa-barcode',
  'icon-tag': 'fa fa-tag',
  'icon-tags': 'fa fa-tags',
  'icon-book': 'fa fa-book',
  'icon-bookmark': 'fa fa-bookmark',
  'icon-print': 'fa fa-print',
  'icon-camera': 'fa fa-camera',
  'icon-font': 'fa fa-font',
  'icon-bold': 'fa fa-bold',
  'icon-italic': 'fa fa-italic',
  'icon-text-height': 'fa fa-text-height',
  'icon-text-width': 'fa fa-text-width',
  'icon-align-left': 'fa fa-align-left',
  'icon-align-center': 'fa fa-align-center',
  'icon-align-right': 'fa fa-align-right',
  'icon-align-justify': 'fa fa-align-justify',
  'icon-list': 'fa fa-list',
  'icon-indent-left': 'fa fa-outdent',
  'icon-indent-right': 'fa fa-indent',
  'icon-facetime-video': 'fa fa-video-camera',
  'icon-picture': 'fa fa-picture-o',
  'icon-pencil': 'fa fa-pencil',
  'icon-map-marker': 'fa fa-map-marker',
  'icon-adjust': 'fa fa-adjust',
  'icon-tint': 'fa fa-tint',
  'icon-edit': 'fa fa-pencil-square-o',
  'icon-share': 'fa fa-share-square-o',
  'icon-check': 'fa fa-check-square-o',
  'icon-move': 'fa fa-arrows',
  'icon-step-backward': 'fa fa-step-backward',
  'icon-fast-backward': 'fa fa-fast-backward',
  'icon-backward': 'fa fa-backward',
  'icon-play': 'fa fa-play',
  'icon-pause': 'fa fa-pause',
  'icon-stop': 'fa fa-stop',
  'icon-forward': 'fa fa-forward',
  'icon-fast-forward': 'fa fa-fast-forward',
  'icon-step-forward': 'fa fa-step-forward',
  'icon-eject': 'fa fa-eject',
  'icon-chevron-left': 'fa fa-chevron-left',
  'icon-chevron-right': 'fa fa-chevron-right',
  'icon-plus-sign': 'fa fa-plus-circle',
  'icon-minus-sign': 'fa fa-minus-circle',
  'icon-remove-sign': 'fa fa-times-circle',
  'icon-ok-sign': 'fa fa-check-circle',
  'icon-question-sign': 'fa fa-question-circle',
  'icon-info-sign': 'fa fa-info-circle',
  'icon-screenshot': 'fa fa-crosshairs',
  'icon-remove-circle': 'fa fa-times-circle-o',
  'icon-ok-circle': 'fa fa-check-circle-o',
  'icon-ban-circle': 'fa fa-ban',
  'icon-arrow-left': 'fa fa-arrow-left',
  'icon-arrow-right': 'fa fa-arrow-right',
  'icon-arrow-up': 'fa fa-arrow-up',
  'icon-arrow-down': 'fa fa-arrow-down',
  'icon-share-alt': 'fa fa-share',
  'icon-resize-full': 'fa fa-expand',
  'icon-resize-small': 'fa fa-compress',
  'icon-plus': 'fa fa-plus',
  'icon-minus': 'fa fa-minus',
  'icon-asterisk': 'fa fa-asterisk',
  'icon-exclamation-sign': 'fa fa-exclamation-circle',
  'icon-gift': 'fa fa-gift',
  'icon-leaf': 'fa fa-leaf',
  'icon-fire': 'fa fa-fire',
  'icon-eye-open': 'fa fa-eye',
  'icon-eye-close': 'fa fa-eye-slash',
  'icon-warning-sign': 'fa fa-exclamation-triangle',
  'icon-plane': 'fa fa-plane',
  'icon-calendar': 'fa fa-calendar',
  'icon-random': 'fa fa-random',
  'icon-comment': 'fa fa-comment',
  'icon-magnet': 'fa fa-magnet',
  'icon-chevron-up': 'fa fa-chevron-up',
  'icon-chevron-down': 'fa fa-chevron-down',
  'icon-retweet': 'fa fa-retweet',
  'icon-shopping-cart': 'fa fa-shopping-cart',
  'icon-folder-close': 'fa fa-folder',
  'icon-folder-open': 'fa fa-folder-open',
  'icon-resize-vertical': 'fa fa-arrows-v',
  'icon-resize-horizontal': 'fa fa-arrows-h',
  'icon-hdd': 'fa fa-hdd-o',
  'icon-bullhorn': 'fa fa-bullhorn',
  'icon-bell': 'fa fa-bell-o',
  'icon-certificate': 'fa fa-certificate',
  'icon-thumbs-up': 'fa fa-thumbs-up',
  'icon-thumbs-down': 'fa fa-thumbs-down',
  'icon-hand-right': 'fa fa-hand-o-right',
  'icon-hand-left': 'fa fa-hand-o-left',
  'icon-hand-up': 'fa fa-hand-o-up',
  'icon-hand-down': 'fa fa-hand-o-down',
  'icon-circle-arrow-right': 'fa fa-arrow-circle-right',
  'icon-circle-arrow-left': 'fa fa-arrow-circle-left',
  'icon-circle-arrow-up': 'fa fa-arrow-circle-up',
  'icon-circle-arrow-down': 'fa fa-arrow-circle-down',
  'icon-globe': 'fa fa-globe',
  'icon-wrench': 'fa fa-wrench',
  'icon-tasks': 'fa fa-tasks',
  'icon-filter': 'fa fa-filter',
  'icon-briefcase': 'fa fa-briefcase',
  'icon-fullscreen': 'fa fa-arrows-alt',
  // FA3 to FA4
  'icon-ban-circle': 'fa fa-ban',
  'icon-bar-chart': 'fa fa-bar-chart-o',
  'icon-beaker': 'fa fa-flask',
  'icon-bell': 'fa fa-bell-o',
  'icon-bell-alt': 'fa fa-bell',
  'icon-bitbucket-sign': 'fa fa-bitbucket-square',
  'icon-bookmark-empty': 'fa fa-bookmark-o',
  'icon-building': 'fa fa-building-o',
  'icon-calendar-empty': 'fa fa-calendar-o',
  'icon-check-empty': 'fa fa-square-o',
  'icon-check-minus': 'fa fa-minus-square-o',
  'icon-check-sign': 'fa fa-check-square',
  'icon-check': 'fa fa-check-square-o',
  'icon-chevron-sign-down': 'fa fa-chevron-down',
  'icon-chevron-sign-left': 'fa fa-chevron-left',
  'icon-chevron-sign-right': 'fa fa-chevron-right',
  'icon-chevron-sign-up': 'fa fa-chevron-up',
  'icon-circle-arrow-down': 'fa fa-arrow-circle-down',
  'icon-circle-arrow-left': 'fa fa-arrow-circle-left',
  'icon-circle-arrow-right': 'fa fa-arrow-circle-right',
  'icon-circle-arrow-up': 'fa fa-arrow-circle-up',
  'icon-circle-blank': 'fa fa-circle-o',
  'icon-cny': 'fa fa-rmb',
  'icon-collapse-alt': 'fa fa-minus-square-o',
  'icon-collapse-top': 'fa fa-caret-square-o-up',
  'icon-collapse': 'fa fa-caret-square-o-down',
  'icon-comment-alt': 'fa fa-comment-o',
  'icon-comments-alt': 'fa fa-comments-o',
  'icon-copy': 'fa fa-files-o',
  'icon-cut': 'fa fa-scissors',
  'icon-dashboard': 'fa fa-tachometer',
  'icon-double-angle-down': 'fa fa-angle-double-down',
  'icon-double-angle-left': 'fa fa-angle-double-left',
  'icon-double-angle-right': 'fa fa-angle-double-right',
  'icon-double-angle-up': 'fa fa-angle-double-up',
  'icon-download': 'fa fa-arrow-circle-o-down',
  'icon-download-alt': 'fa fa-download',
  'icon-edit-sign': 'fa fa-pencil-square',
  'icon-edit': 'fa fa-pencil-square-o',
  'icon-ellipsis-horizontal': 'fa fa-ellipsis-h',
  'icon-ellipsis-vertical': 'fa fa-ellipsis-v',
  'icon-envelope-alt': 'fa fa-envelope-o',
  'icon-exclamation-sign': 'fa fa-exclamation-circle',
  'icon-expand-alt': 'fa fa-plus-square-o',
  'icon-expand': 'fa fa-caret-square-o-right',
  'icon-external-link-sign': 'fa fa-external-link-square',
  'icon-eye-close': 'fa fa-eye-slash',
  'icon-eye-open': 'fa fa-eye',
  'icon-facebook-sign': 'fa fa-facebook-square',
  'icon-facetime-video': 'fa fa-video-camera',
  'icon-file-alt': 'fa fa-file-o',
  'icon-file-text-alt': 'fa fa-file-text-o',
  'icon-flag-alt': 'fa fa-flag-o',
  'icon-folder-close-alt': 'fa fa-folder-o',
  'icon-folder-close': 'fa fa-folder',
  'icon-folder-open-alt': 'fa fa-folder-open-o',
  'icon-food': 'fa fa-cutlery',
  'icon-frown': 'fa fa-frown-o',
  'icon-fullscreen': 'fa fa-arrows-alt',
  'icon-github-sign': 'fa fa-github-square',
  'icon-google-plus-sign': 'fa fa-google-plus-square',
  'icon-group': 'fa fa-users',
  'icon-h-sign': 'fa fa-h-square',
  'icon-hand-down': 'fa fa-hand-o-down',
  'icon-hand-left': 'fa fa-hand-o-left',
  'icon-hand-right': 'fa fa-hand-o-right',
  'icon-hand-up': 'fa fa-hand-o-up',
  'icon-hdd': 'fa fa-hdd-o',
  'icon-heart-empty': 'fa fa-heart-o',
  'icon-hospital': 'fa fa-hospital-o',
  'icon-indent-left': 'fa fa-outdent',
  'icon-indent-right': 'fa fa-indent',
  'icon-info-sign': 'fa fa-info-circle',
  'icon-keyboard': 'fa fa-keyboard-o',
  'icon-legal': 'fa fa-gavel',
  'icon-lemon': 'fa fa-lemon-o',
  'icon-lightbulb': 'fa fa-lightbulb-o',
  'icon-linkedin-sign': 'fa fa-linkedin-square',
  'icon-meh': 'fa fa-meh-o',
  'icon-microphone-off': 'fa fa-microphone-slash',
  'icon-minus-sign-alt': 'fa fa-minus-square',
  'icon-minus-sign': 'fa fa-minus-circle',
  'icon-mobile-phone': 'fa fa-mobile',
  'icon-moon': 'fa fa-moon-o',
  'icon-move': 'fa fa-arrows',
  'icon-off': 'fa fa-power-off',
  'icon-ok-circle': 'fa fa-check-circle-o',
  'icon-ok-sign': 'fa fa-check-circle',
  'icon-ok': 'fa fa-check',
  'icon-paper-clip': 'fa fa-paperclip',
  'icon-paste': 'fa fa-clipboard',
  'icon-phone-sign': 'fa fa-phone-square',
  'icon-picture': 'fa fa-picture-o',
  'icon-pinterest-sign': 'fa fa-pinterest-square',
  'icon-play-circle': 'fa fa-play-circle-o',
  'icon-play-sign': 'fa fa-play-circle',
  'icon-plus-sign-alt': 'fa fa-plus-square',
  'icon-plus-sign': 'fa fa-plus-circle',
  'icon-pushpin': 'fa fa-thumb-tack',
  'icon-question-sign': 'fa fa-question-circle',
  'icon-remove-circle': 'fa fa-times-circle-o',
  'icon-remove-sign': 'fa fa-times-circle',
  'icon-remove': 'fa fa-times',
  'icon-reorder': 'fa fa-bars',
  'icon-resize-full': 'fa fa-expand',
  'icon-resize-horizontal': 'fa fa-arrows-h',
  'icon-resize-small': 'fa fa-compress',
  'icon-resize-vertical': 'fa fa-arrows-v',
  'icon-rss-sign': 'fa fa-rss-square',
  'icon-save': 'fa fa-floppy-o',
  'icon-screenshot': 'fa fa-crosshairs',
  'icon-share-alt': 'fa fa-share',
  'icon-share-sign': 'fa fa-share-square',
  'icon-share': 'fa fa-share-square-o',
  'icon-sign-blank': 'fa fa-square',
  'icon-signin': 'fa fa-sign-in',
  'icon-signout': 'fa fa-sign-out',
  'icon-smile': 'fa fa-smile-o',
  'icon-sort-by-alphabet-alt': 'fa fa-sort-alpha-desc',
  'icon-sort-by-alphabet': 'fa fa-sort-alpha-asc',
  'icon-sort-by-attributes-alt': 'fa fa-sort-amount-desc',
  'icon-sort-by-attributes': 'fa fa-sort-amount-asc',
  'icon-sort-by-order-alt': 'fa fa-sort-numeric-desc',
  'icon-sort-by-order': 'fa fa-sort-numeric-asc',
  'icon-sort-down': 'fa fa-sort-desc',
  'icon-sort-up': 'fa fa-sort-asc',
  'icon-stackexchange': 'fa fa-stack-overflow',
  'icon-star-empty': 'fa fa-star-o',
  'icon-star-half-empty': 'fa fa-star-half-o',
  'icon-sun': 'fa fa-sun-o',
  'icon-thumbs-down-alt': 'fa fa-thumbs-o-down',
  'icon-thumbs-up-alt': 'fa fa-thumbs-o-up',
  'icon-time': 'fa fa-clock-o',
  'icon-trash': 'fa fa-trash-o',
  'icon-tumblr-sign': 'fa fa-tumblr-square',
  'icon-twitter-sign': 'fa fa-twitter-square',
  'icon-unlink': 'fa fa-chain-broken',
  'icon-upload': 'fa fa-arrow-circle-o-up',
  'icon-upload-alt': 'fa fa-upload',
  'icon-warning-sign': 'fa fa-exclamation-triangle',
  'icon-xing-sign': 'fa fa-xing-square',
  'icon-youtube-sign': 'fa fa-youtube-square',
  'icon-zoom-in': 'fa fa-search-plus',
  'icon-zoom-out': 'fa fa-search-minus',
  // common BS2 or FA3 to FA4
  'icon-fixed-width': 'fa-fw',
  'icon-large': 'fa-lg',
  'icons-ul': 'fa-ul',
  'icon-li': 'fa-li',
  'icon-spin': 'fa-spin',
  'icon-rotate-90': 'fa-rotate-90',
  'icon-rotate-180': 'fa-rotate-180',
  'icon-rotate-270': 'fa-rotate-270',
  'icon-white': 'fa-inverse',
  'icon-large': 'fa-lg',
  'icon-2x': 'fa-2x',
  'icon-3x': 'fa-3x',
  'icon-4x': 'fa-4x',
  // BS3 to FA4
  'glyphicon-adjust': 'fa-adjust',
  'glyphicon-alert': 'fa-exclamation-triangle',
  'glyphicon-align-center': 'fa-align-center',
  'glyphicon-align-justify': 'fa-align-justify',
  'glyphicon-align-left': 'fa-align-left',
  'glyphicon-align-right': 'fa-align-right',
  'glyphicon-apple': 'fa-apple',
  'glyphicon-arrow-down': 'fa-arrow-down',
  'glyphicon-arrow-left': 'fa-arrow-left',
  'glyphicon-arrow-right': 'fa-arrow-right',
  'glyphicon-arrow-up': 'fa-arrow-up',
  'glyphicon-asterisk': 'fa-asterisk',
  'glyphicon-baby-formula': 'fa-question',
  'glyphicon-backward': 'fa-backward',
  'glyphicon-ban-circle': 'fa-ban',
  'glyphicon-barcode': 'fa-barcode',
  'glyphicon-bed': 'fa-bed',
  'glyphicon-bell': 'fa-bell',
  'glyphicon-bishop': 'fa-question',
  'glyphicon-bitcoin': 'fa-bitcoin',
  'glyphicon-blackboard': 'fa-question',
  'glyphicon-bold': 'fa-bold',
  'glyphicon-book': 'fa-book',
  'glyphicon-bookmark': 'fa-bookmark',
  'glyphicon-briefcase': 'fa-briefcase',
  'glyphicon-btc': 'fa-btc',
  'glyphicon-bullhorn': 'fa-bullhorn',
  'glyphicon-calendar': 'fa-calendar',
  'glyphicon-camera': 'fa-camera',
  'glyphicon-cd': 'fa-dot-circle-o',
  'glyphicon-certificate': 'fa-certificate',
  'glyphicon-check': 'fa-check',
  'glyphicon-chevron-down': 'fa-chevron-down',
  'glyphicon-chevron-left': 'fa-chevron-left',
  'glyphicon-chevron-right': 'fa-chevron-right',
  'glyphicon-chevron-up': 'fa-chevron-up',
  'glyphicon-circle-arrow-down': 'fa-arrow-circle-down',
  'glyphicon-circle-arrow-left': 'fa-arrow-circle-left',
  'glyphicon-circle-arrow-right': 'fa-arrow-circle-right',
  'glyphicon-circle-arrow-up': 'fa-arrow-circle-up',
  'glyphicon-cloud': 'fa-cloud',
  'glyphicon-cloud-download': 'fa-cloud-download',
  'glyphicon-cloud-upload': 'fa-cloud-upload',
  'glyphicon-cog': 'fa-cog',
  'glyphicon-collapse-down': 'fa-caret-square-o-down',
  'glyphicon-collapse-up': 'fa-caret-square-o-up',
  'glyphicon-comment': 'fa-comment',
  'glyphicon-compressed': 'fa-file-archive-o',
  'glyphicon-console': 'fa-terminal',
  'glyphicon-copy': 'fa-copy',
  'glyphicon-copyright-mark': 'fa-copyright',
  'glyphicon-credit-card': 'fa-credit-card',
  'glyphicon-cutlery': 'fa-cutlery',
  'glyphicon-dashboard': 'fa-dashboard',
  'glyphicon-download': 'fa-download',
  'glyphicon-download-alt': 'fa-cloud-download',
  'glyphicon-duplicate': 'fa-files-o',
  'glyphicon-earphone': 'fa-phone',
  'glyphicon-edit': 'fa-edit',
  'glyphicon-education': 'fa-graduation-cap',
  'glyphicon-eject': 'fa-eject',
  'glyphicon-envelope': 'fa-envelope',
  'glyphicon-equalizer': 'fa-bar-chart',
  'glyphicon-erase': 'fa-eraser',
  'glyphicon-eur': 'fa-eur',
  'glyphicon-euro': 'fa-eur',
  'glyphicon-exclamation-sign': 'fa-exclamation-circle',
  'glyphicon-expand': 'fa-caret-square-o-right',
  'glyphicon-export': 'fa-download',
  'glyphicon-eye-close': 'fa-eye-slash',
  'glyphicon-eye-open': 'fa-eye',
  'glyphicon-facetime-video': 'fa-video-camera',
  'glyphicon-fast-backward': 'fa-fast-backward',
  'glyphicon-fast-forward': 'fa-fast-forward',
  'glyphicon-file': 'fa-file',
  'glyphicon-film': 'fa-film',
  'glyphicon-filter': 'fa-filter',
  'glyphicon-fire': 'fa-fire',
  'glyphicon-flag': 'fa-flag',
  'glyphicon-flash': 'fa-flash',
  'glyphicon-floppy-disk': 'fa-save',
  'glyphicon-floppy-open': 'fa-upload',
  'glyphicon-floppy-remove': 'fa-remove',
  'glyphicon-floppy-save': 'fa-download',
  'glyphicon-floppy-saved': 'fa-check',
  'glyphicon-folder-close': 'fa-folder',
  'glyphicon-folder-open': 'fa-folder-open',
  'glyphicon-font': 'fa-font',
  'glyphicon-forward': 'fa-forward',
  'glyphicon-fullscreen': 'fa-expand',
  'glyphicon-gbp': 'fa-gbp',
  'glyphicon-gift': 'fa-gift',
  'glyphicon-glass': 'fa-glass',
  'glyphicon-globe': 'fa-globe',
  'glyphicon-grain': 'fa-question',
  'glyphicon-hand-down': 'fa-hand-o-down',
  'glyphicon-hand-left': 'fa-hand-o-left',
  'glyphicon-hand-right': 'fa-hand-o-right',
  'glyphicon-hand-up': 'fa-hand-o-up',
  'glyphicon-hd-video': 'fa-film',
  'glyphicon-hdd': 'fa-hdd-o',
  'glyphicon-header': 'fa-header',
  'glyphicon-headphones': 'fa-headphones',
  'glyphicon-heart': 'fa-heart',
  'glyphicon-heart-empty': 'fa-heart-o',
  'glyphicon-home': 'fa-home',
  'glyphicon-hourglass': 'fa-hourglass',
  'glyphicon-ice-lolly': 'fa-question',
  'glyphicon-ice-lolly-tasted': 'fa-question',
  'glyphicon-import': 'fa-upload',
  'glyphicon-inbox': 'fa-inbox',
  'glyphicon-indent-left': 'fa-indent',
  'glyphicon-indent-right': 'fa-outdent',
  'glyphicon-info-sign': 'fa-info-circle',
  'glyphicon-italic': 'fa-italic',
  'glyphicon-jpy': 'fa-jpy',
  'glyphicon-king': 'fa-question',
  'glyphicon-knight': 'fa-question',
  'glyphicon-lamp': 'fa-lightbulb-o',
  'glyphicon-leaf': 'fa-leaf',
  'glyphicon-level-up': 'fa-level-up',
  'glyphicon-link': 'fa-link',
  'glyphicon-list': 'fa-list',
  'glyphicon-list-alt': 'fa-list-alt',
  'glyphicon-lock': 'fa-lock',
  'glyphicon-log-in': 'fa-sign-in',
  'glyphicon-log-out': 'fa-sign-out',
  'glyphicon-magnet': 'fa-magnet',
  'glyphicon-map-marker': 'fa-map-marker',
  'glyphicon-menu-down': 'fa-chevron-down',
  'glyphicon-menu-hamburger': 'fa-bars',
  'glyphicon-menu-left': 'fa-chevron-left',
  'glyphicon-menu-right': 'fa-chevron-right',
  'glyphicon-menu-up': 'fa-chevron-up',
  'glyphicon-minus': 'fa-minus',
  'glyphicon-minus-sign': 'fa-minus-circle',
  'glyphicon-modal-window': 'fa-question',
  'glyphicon-move': 'fa-arrows',
  'glyphicon-music': 'fa-music',
  'glyphicon-new-window': 'fa-external-link',
  'glyphicon-object-align-bottom': 'fa-question',
  'glyphicon-object-align-horizontal': 'fa-question',
  'glyphicon-object-align-left': 'fa-question',
  'glyphicon-object-align-right': 'fa-question',
  'glyphicon-object-align-top': 'fa-question',
  'glyphicon-object-align-vertical': 'fa-question',
  'glyphicon-off': 'fa-power-off',
  'glyphicon-oil': 'fa-question',
  'glyphicon-ok': 'fa-check',
  'glyphicon-ok-circle': 'fa-check-circle',
  'glyphicon-ok-sign': 'fa-check-circle',
  'glyphicon-open': 'fa-upload',
  'glyphicon-open-file': 'fa-folder-open-o',
  'glyphicon-option-horizontal': 'fa-ellipsis-h',
  'glyphicon-option-vertical': 'fa-ellipsis-v',
  'glyphicon-paperclip': 'fa-paperclip',
  'glyphicon-paste': 'fa-paste',
  'glyphicon-pause': 'fa-pause',
  'glyphicon-pawn': 'fa-question',
  'glyphicon-pencil': 'fa-pencil',
  'glyphicon-phone': 'fa-phone',
  'glyphicon-phone-alt': 'fa-phone-square',
  'glyphicon-picture': 'fa-picture-o',
  'glyphicon-piggy-bank': 'fa-money',
  'glyphicon-plane': 'fa-plane',
  'glyphicon-play': 'fa-play',
  'glyphicon-play-circle': 'fa-play-circle',
  'glyphicon-plus': 'fa-plus',
  'glyphicon-plus-sign': 'fa-plus-circle',
  'glyphicon-print': 'fa-print',
  'glyphicon-pushpin': 'fa-thumb-tack',
  'glyphicon-qrcode': 'fa-qrcode',
  'glyphicon-queen': 'fa-question',
  'glyphicon-question-sign': 'fa-question-circle',
  'glyphicon-random': 'fa-random',
  'glyphicon-record': 'fa-dot-circle-o',
  'glyphicon-refresh': 'fa-refresh',
  'glyphicon-registration-mark': 'fa-registered',
  'glyphicon-remove': 'fa-remove',
  'glyphicon-remove-circle': 'fa-times-circle',
  'glyphicon-remove-sign': 'fa-times-circle',
  'glyphicon-repeat': 'fa-repeat',
  'glyphicon-resize-full': 'fa-expand',
  'glyphicon-resize-horizontal': 'fa-arrows-h',
  'glyphicon-resize-small': 'fa-compress',
  'glyphicon-resize-vertical': 'fa-arrows-v',
  'glyphicon-retweet': 'fa-retweet',
  'glyphicon-road': 'fa-road',
  'glyphicon-rub': 'fa-rub',
  'glyphicon-ruble': 'fa-ruble',
  'glyphicon-save': 'fa-save',
  'glyphicon-save-file': 'fa-save',
  'glyphicon-saved': 'fa-check',
  'glyphicon-scale': 'fa-balance-scale',
  'glyphicon-scissors': 'fa-scissors',
  'glyphicon-screenshot': 'fa-crosshairs',
  'glyphicon-sd-video': 'fa-film',
  'glyphicon-search': 'fa-search',
  'glyphicon-send': 'fa-paper-plane-o',
  'glyphicon-share': 'fa-share',
  'glyphicon-share-alt': 'fa-share-alt',
  'glyphicon-shopping-cart': 'fa-shopping-cart',
  'glyphicon-signal': 'fa-signal',
  'glyphicon-sort': 'fa-sort',
  'glyphicon-sort-by-alphabet': 'fa-sort-alpha-asc',
  'glyphicon-sort-by-alphabet-alt': 'fa-sort-alpha-desc',
  'glyphicon-sort-by-attributes': 'fa-sort-amount-asc',
  'glyphicon-sort-by-attributes-alt': 'fa-sort-amount-desc',
  'glyphicon-sort-by-order': 'fa-sort-numeric-asc',
  'glyphicon-sort-by-order-alt': 'fa-sort-numeric-desc',
  'glyphicon-sound-5-1': 'fa-music',
  'glyphicon-sound-6-1': 'fa-music',
  'glyphicon-sound-7-1': 'fa-music',
  'glyphicon-sound-dolby': 'fa-music',
  'glyphicon-sound-stereo': 'fa-music',
  'glyphicon-star': 'fa-star',
  'glyphicon-star-empty': 'fa-star-o',
  'glyphicon-stats': 'fa-bar-chart',
  'glyphicon-step-backward': 'fa-step-backward',
  'glyphicon-step-forward': 'fa-step-forward',
  'glyphicon-stop': 'fa-stop',
  'glyphicon-subscript': 'fa-subscript',
  'glyphicon-subtitles': 'fa-cc',
  'glyphicon-sunglasses': 'fa-question',
  'glyphicon-superscript': 'fa-superscript',
  'glyphicon-tag': 'fa-tag',
  'glyphicon-tags': 'fa-tags',
  'glyphicon-tasks': 'fa-tasks',
  'glyphicon-tent': 'fa-question',
  'glyphicon-text-background': 'fa-font',
  'glyphicon-text-color': 'fa-font',
  'glyphicon-text-height': 'fa-text-height',
  'glyphicon-text-size': 'fa-font',
  'glyphicon-text-width': 'fa-text-width',
  'glyphicon-th': 'fa-th',
  'glyphicon-th-large': 'fa-th-large',
  'glyphicon-th-list': 'fa-th-list',
  'glyphicon-thumbs-down': 'fa-thumbs-down',
  'glyphicon-thumbs-up': 'fa-thumbs-up',
  'glyphicon-time': 'fa-clock-o',
  'glyphicon-tint': 'fa-tint',
  'glyphicon-tower': 'fa-building',
  'glyphicon-transfer': 'fa-exchange',
  'glyphicon-trash': 'fa-trash',
  'glyphicon-tree-conifer': 'fa-tree',
  'glyphicon-tree-deciduous': 'fa-tree',
  'glyphicon-triangle-bottom': 'fa-caret-down',
  'glyphicon-triangle-left': 'fa-caret-left',
  'glyphicon-triangle-right': 'fa-caret-right',
  'glyphicon-triangle-top': 'fa-caret-up',
  'glyphicon-unchecked': 'fa-square-o',
  'glyphicon-upload': 'fa-upload',
  'glyphicon-usd': 'fa-usd',
  'glyphicon-user': 'fa-user',
  'glyphicon-volume-down': 'fa-volume-down',
  'glyphicon-volume-off': 'fa-volume-off',
  'glyphicon-volume-up': 'fa-volume-up',
  'glyphicon-warning-sign': 'fa-exclamation-triangle',
  'glyphicon-wrench': 'fa-wrench',
  'glyphicon-xbt': 'fa-btc',
  'glyphicon-yen': 'fa-yen',
  'glyphicon-zoom-in': 'fa-search-plus',
  'glyphicon-zoom-out': 'fa-search-minus'
}


var consoleColors = require('colors'),
  fs = require('fs'),
  path = require('path');

console.log('Welcome to fonteroni!'.rainbow);

try {
  fs.unlinkSync('result.html');
}
catch (e) {
}

var args = process.argv.slice(2);
if (args.length == 0) {
  console.log('Usage: node index.js PATH_TO_YOUR_FOLDER [--preview]')
  console.log('or')
  console.log('node index.js ICON_NAME_YOU_WANT_TO_CONVERT')
}
else {
  console.log('Starting...');
  console.log(('Loaded ' + Object.keys(MAPPING).length + ' icon mappings').green);

  if (args[0].toLowerCase().indexOf('icon') == 0 || args[0].toLowerCase().indexOf('glyphicon') == 0) {
    if (MAPPING[args[0].toLowerCase()]) {
      console.log('\t', args[0].red, '=>', MAPPING[args[0].toLowerCase()].green);
    }
    else {
      console.log('\t', 'Icon', args[0].red, 'NOT FOUND');
    }
  }

  else {
    var finder = require('findit')(args[0]);

    finder.on('directory', function (dir, stat, stop) {
      var base = path.basename(dir);
      if (base === '.git' || base === 'node_modules') stop()
    });

    finder.on('file', function (file) {
      var baseName = path.basename(file);
      var readIt = false;
      CHANGE_VARIABLES_EXTENSIONS.forEach(function (ext) {
        if (baseName.toLowerCase().indexOf(ext) > -1) {
          readIt = true;
        }
      });
      FORCE_SKIPPED_EXTENSIONS.forEach(function (ext) {
        if (baseName.toLowerCase().indexOf(ext) > -1) {
          readIt = false;
        }
      });
      if (readIt) {
        fs.readFile(file, 'utf8', function (err, data) {
          if (err) {
            return console.log(err);
          }

          var matches;
          var re = /((?:\w+-)+\w+)/gi;
          console.log(file);
          while (matches = re.exec(data)) {
            if (matches.index === re.lastIndex) {
              re.lastIndex++;
            }
            if (matches[0].indexOf('icon-') > -1) {
              if (MAPPING[matches[0].toLowerCase()]) {
                console.log('\t', matches[0].red, '=>', MAPPING[matches[0].toLowerCase()].green);
              }
              else {
                console.log('\t', 'Icon', matches[0].red, 'NOT FOUND');
              }
              console.log('--')
            }
          }
          if (args[1] == null || args[1] !== '--preview') {
            var result = data.replace(re, function ($1) {
              return MAPPING[$1.toLowerCase()] ? MAPPING[$1.toLowerCase()] : $1;
            }).replace(/glyphicon/gi, 'fa');
            fs.writeFile(file, result, 'utf8', function (err) {
              if (err) {
                return console.log(err);
              }
            });
          }
        });
      }
    });
  }
}
